name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feat'

  - title: 'Bug Fixes'
    labels:
      - 'fix'

  - title: 'Maintenance'
    label: 'chore'

  - title: 'Documentation'
    label: 'docs'

  - title: 'Continuos Integration'
    label: 'ci'

  - title: 'Build'
    label: 'build'

  - title: 'Performance'
    label: 'perf'

  - title: 'Refactor'
    label: 'refactor'

  - title: 'Style'
    label: 'style'

  - title: 'Test'
    label: 'test'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Getting the project
  Get Docker Image from Dockerhub: https://hub.docker.com/r/luisfalconmx/strapi
  Get Docker Image from Github Container Registry: https://github.com/users/luisfalconmx/packages/container/package/strapi
  License: https://github.com/luisfalconmx/strapi/blob/main/LICENSE
  Code of Conduct: https://github.com/luisfalconmx/strapi/blob/main/CODE_OF_CONDUCT.md
  Guides: https://github.com/luisfalconmx/strapi#guides

  ## New in Strapi v$RESOLVED_VERSION

  $CHANGES
